Service graphs documentation
grafana/tempo pull request #1106
Opened 2021-11-09 11:18 UTC by mapno

**What this PR does**:

Adds documentation for _Service Graphs_.

The images added are the following:

![image](https://user-images.githubusercontent.com/39532714/140914792-8cadf533-add7-4a6c-aa78-d09ac424249d.png)

![service-graphs-agent-architecture](https://user-images.githubusercontent.com/39532714/140914814-370a4c02-0180-4d2a-a29e-59d5c4777e1e.png)

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-11-11 11:23 UTC, mapno commented on docs/tempo/website/grafana-agent/service-graphs.md
> +Service graphs works by inspecting spans and looking for the tag `span.kind`.
Added

2021-11-11 11:23 UTC, mapno commented on docs/tempo/website/grafana-agent/service-graphs.md
> +To see all the available config options, refer to the [configuration reference](https://github.com/grafana/agent/blob/main/docs/configuration/traces-config.md).
Yeah, good suggestion. Added

2021-11-11 11:24 UTC, mapno commented on docs/tempo/website/grafana-agent/service-graphs.md
> +### Grafana
Good idea. I added a minimal example. Thanks

2021-11-11 17:30 UTC, kvrhdn approved these changes
This looks good to me, the technical details look right :+1: I think a review from @KMiller-Grafana will be very valuable as well before merging.

2021-11-16 19:17 UTC, KMiller-Grafana requested changes
Lots of improvement suggestions!

2021-11-16 19:17 UTC, KMiller-Grafana commented on docs/tempo/website/grafana-agent/service-graphs.md
> +Let’s call this amount hops. Every hop will be a unique combination of client + server labels.
```suggestion
There isn't a direct formula or solution to the cardinality problem,
but the following guide should help estimate the cardinality that the feature will generate.

The quantity of graph edges depend on both the quantity of nodes in the distributed system and the direction of the requests between the nodes.
Call the quantity of edges to be hops. Every hop will be a unique combination of client plus server labels.
```

2021-11-16 19:17 UTC, KMiller-Grafana commented on docs/tempo/website/grafana-agent/service-graphs.md
> +If we know the amount of hops in a system, we can calculate the cardinality of the generated service graphs:
```suggestion
- a fully-connected system with 3 nodes `(A, B, C)` will have 6 hops `(A → B, B → A, B → C, C → B, A → C, C → A)`

We can’t calculate hops automatically based upon the nodes,
but it should be a value between the `number of services - 1` and  `the number of services!`.

If we know the hops in a system, we can calculate the cardinality of the generated service graph:
```

2021-11-16 19:17 UTC, KMiller-Grafana commented on docs/tempo/website/grafana-agent/service-graphs.md
> +Finally, we get the following cardinality estimation:
```suggestion
  service_graph_request_total: number of hops
  service_graph_request_failed_total: number of hops
  service_graph_request_server_seconds: 3 buckets * number of hops
  service_graph_request_client_seconds: 3 buckets * number of hops
  service_graph_unpaired_spans_total: number of services (absolute worst case)
  service_graph_dropped_spans_total: number of services (absolute worst case)
```

The cardinality estimation becomes:
```

2021-11-16 19:17 UTC, KMiller-Grafana commented on docs/tempo/website/grafana-agent/tail-based-sampling.md
> +To see all the available config options, refer to the [configuration reference](https://grafana.com/docs/agent/latest/configuration/traces-config/).
```suggestion
To see all the available configuration options, refer to the [traces_config](https://grafana.com/docs/agent/latest/configuration/traces-config/) configuration reference.
```

2021-11-19 16:17 UTC, KMiller-Grafana approved these changes
Thanks for all the changes.  LGTM.

2021-11-22 11:09 UTC, merged