Add overrides configmap to querier, update docs for new limit
grafana/tempo pull request #1153
Opened 2021-12-03 08:11 UTC by annanay25

Signed-off-by: Annanay <annanayagarwal@gmail.com>

**What this PR does**:
- [Jsonnet] Add overrides confimap to the querier
- [Docs] Add docs for the new limit and revamp the overrides section a bit

**Which issue(s) this PR fixes**:
Follow up from #1068 

Marking draft because this is 100% going to collide with #1129 

**Checklist**
- NA Tests updated
- [x] Documentation added
- NA `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-12-03 10:38 UTC, mapno approved these changes
LGTM

2021-12-03 19:11 UTC, KMiller-Grafana requested changes

2021-12-03 19:11 UTC, KMiller-Grafana commented on docs/tempo/website/configuration/_index.md
> +    # individually OR should be shared across all replicas. See the "override strategies" section below for an example.
Wording suggestions here are to attempt to use similar terms across all documentation.  Here, we're talking about components, so I've substituted "instance" for "replica." 

```suggestion
    # Specifies whether the ingestion rate limits should be applied by each instance of the distributor and ingester
    # individually, or the limits are to be shared across all instances. See the "override strategies" section for an example.
```

2021-12-03 19:11 UTC, KMiller-Grafana commented on docs/tempo/website/configuration/_index.md
> +    # Limit added to protect from tags with high cardinality or large values (like http urls or sql queries)
```suggestion
    # Limit added to protect from tags with high cardinality or large values (like HTTP URLs or SQL queries)
```

2021-12-03 19:11 UTC, KMiller-Grafana commented on docs/tempo/website/configuration/_index.md
> +    # Tenant-specific overrides settings config file. See the "Tenant-specific overrides" section below for an example.
Note:  "config" is not a word (or an abbreviation). 
```suggestion
    # Tenant-specific overrides settings configuration file. See the "Tenant-specific overrides" section for an example.
```

2021-12-03 19:11 UTC, KMiller-Grafana commented on docs/tempo/website/configuration/_index.md
> +For ex, the config below specifies that each replica of the distributor will apply a limit of `15MB/s`.
```suggestion
For example, this configuration specifies that each instance of the distributor will apply a limit of `15MB/s`.
```

2021-12-03 19:11 UTC, KMiller-Grafana commented on docs/tempo/website/configuration/_index.md
> +So if there are 5 replicas, each will apply a local limit of `(15MB/s / 5) = 3MB/s`.
```suggestion
This configuration specifies that together, all distributor instances will apply a limit of `15MB/s`.
So if there are 5 instances, each instance will apply a local limit of `(15MB/s / 5) = 3MB/s`.
```

2021-12-06 11:27 UTC, annanay25 commented
@KMiller-Grafana Thanks for the review. I'm going to merge this one as I have addressed your comments. There were no other docs changes.

2021-12-06 22:08 UTC, KMiller-Grafana approved these changes
Docs look good to me now.  Thanks for the changes.

2021-12-06 22:08 UTC, merged