Remove tenant_header_key from config
grafana/tempo pull request #2414
Opened 2023-05-01 16:31 UTC by kousikmitra

**What this PR does**:

Removes `tenant_header_key` option from config

**Which issue(s) this PR fixes**:
Fixes #2381

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-05-02 13:44 UTC, mdisibio requested changes
Hi thanks for the cleanup.  Just one small nit in the changelog and LGTM

2023-05-02 13:44 UTC, mdisibio commented on CHANGELOG.md
> +* [ENHANCEMENT] Remove `tenant_header_key` option from `tempo-query` config [#2414](https://github.com/grafana/tempo/pull/2414) (@kousikmitra)
I think this should be `[CHANGE]`

2023-05-02 16:00 UTC, kousikmitra commented on CHANGELOG.md
> +* [ENHANCEMENT] Remove `tenant_header_key` option from `tempo-query` config [#2414](https://github.com/grafana/tempo/pull/2414) (@kousikmitra)
Updated

2023-05-04 09:52 UTC, mapno approved these changes
LGTM. Can you fix the conflict?

2023-05-05 12:44 UTC, mdisibio approved these changes

2023-05-05 12:44 UTC, merged