[DOC] Update README.md
grafana/tempo pull request #3349
Opened 2024-01-30 19:18 UTC by knylander-grafana

Add instructions on how to use the mixins.

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Tests updated
- [X] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2024-01-30 19:19 UTC, knylander-grafana commented on operations/tempo-mixin/README.md
> +Once installed, Dashboards, rules, and alerts are in the [`yamls`](./yamls) folder. Use them directly in Prometheus & Grafana to monitor Tempo.
```suggestion
Once installed, dashboards, rules, and alerts are in the [`yamls`](./yamls) folder. Use them directly in Prometheus and Grafana to monitor Tempo.
```

2024-01-30 19:31 UTC, hedss requested changes
Only comment :)

2024-01-30 19:31 UTC, hedss commented on operations/tempo-mixin/README.md
> +Once installed, dashboards, rules, and alerts are in the [`yamls`](./yamls) folder. Use them directly in Prometheus and Grafana to monitor Tempo.
```suggestion
Once installed via the build instructions below, dashboards, rules, and alerts are located in the [`operations/tempo-mixins-compiled`](..tempo-mixins-compiled) folder. Use them directly in Prometheus and Grafana to monitor Tempo.
```

2024-02-01 03:58 UTC, hedss approved these changes

2024-02-01 14:37 UTC, merged