chore: add query-frontend option to select request headers in query logs
grafana/tempo pull request #3383
Opened 2024-02-12 17:15 UTC by jmichalek132

**What this PR does**:

Adding feature present in mimir and LOKI, specifically https://github.com/grafana/mimir/pull/5030 and https://github.com/grafana/loki/issues/11422.

Adds a config option to the query-frontend to specify a list of request headers to include in query logs.

For example, setting -query-frontend.log-query-request-headers="X-Grafana-Org-Id" and sending a query with X-Grafana-Org-Id:1 results in query log lines that include header_x_grafana_org_id=1.

**Which issue(s) this PR fixes**:
Fixes #3342

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2024-02-14 20:21 UTC, jmichalek132 commented
For the pipeline failure, the test fails looks unrelated to my change:
```
tenant=0 component=remote level=info remote_name=ce2f78 url=http://127.0.0.1:35569/receive msg="Scraped metadata watcher stopped"
    instance_test.go:140: 
        	Error Trace:	/home/runner/work/tempo/tempo/modules/generator/storage/instance_test.go:140
        	            				/home/runner/work/tempo/tempo/modules/generator/storage/instance_test.go:340
        	            				/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Received unexpected error:
        	            	write /tmp/TestInstance_multiTenancy3811487438/001/0/wal/00000000: file already closed
        	Test:       	TestInstance_multiTenancy
tenant=0 component=remote level=info remote_name=ce2f78 url=http://127.0.0.1:35569/receive msg="Remote storage stopped."
```

For the linting I ran `make lint` locally as instructed by the contributing guide, but it came up with many complaints for code I didn't touch, so unsure how to address that.

2024-02-15 10:40 UTC, mapno requested changes
LGTM, only to minor things.

2024-02-15 10:40 UTC, mapno commented on modules/frontend/handler.go
> +	})
This should get rid of the lint error

```suggestion
	logMessage := []interface{}{
		"tenant", orgID,
		"method", r.Method,
		"traceID", traceID,
		"url", r.URL.RequestURI(),
		"duration", elapsed.String(),
	}
```

2024-02-15 10:40 UTC, mapno commented on modules/frontend/handler.go
> +	LogQueryRequestHeaders flagext.StringSliceCSV
This can be lowercase, no need to export it

```suggestion
	logQueryRequestHeaders flagext.StringSliceCSV
```

2024-02-15 12:31 UTC, joe-elliott commented
> For the pipeline failure, the test fails looks unrelated to my change:

Don't worry about this. CI flakiness. We can ignore this error.

2024-02-23 09:40 UTC, mapno approved these changes
LGTM. Thanks!

2024-02-23 09:41 UTC, mapno commented
Ups, it seems the `logQueryRequestHeaders` wasn't correctly updated everywhere. When that's fixed I'll merge cc/ @jmichalek132

2024-02-25 15:44 UTC, jmichalek132 commented
> Ups, it seems the `logQueryRequestHeaders` wasn't correctly updated everywhere. When that's fixed I'll merge cc/ @jmichalek132

Sorry for the delay, fixed now.

2024-02-26 11:14 UTC, merged