Add metric tempodb_compaction_objects_processed_total
grafana/tempo pull request #360
Opened 2020-11-19 20:46 UTC by mdisibio

**What this PR does**:
Adds a new metric `tempodb_compaction_objects_processed_total` which is incremented for every object processed during compaction. This can be used to calculate the rate() at which compactors are working, and estimate capacity.

**Which issue(s) this PR fixes**:
n/a

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2020-11-20 02:36 UTC, joe-elliott reviewed
Should we drop `metricCompactionDuration`?  I feel like that metric loses it's meaning with the variable block compactions.

Also, what do you think about `tempodb_compaction_blocks_total{level=''}`.  A counter that increments once for every processed block of each level.  We could drop the duration histogram while still having some vision on which compactors are compacting blocks at which levels.

Oh, and feel free to add any of this to the operational dashboard that makes sense.  I think there's a compaction section now.

2020-11-20 16:51 UTC, mdisibio commented
> Should we drop `metricCompactionDuration`? I feel like that metric loses it's meaning with the variable block compactions.
> 
> Also, what do you think about `tempodb_compaction_blocks_total{level=''}`. A counter that increments once for every processed block of each level. We could drop the duration histogram while still having some vision on which compactors are compacting blocks at which levels.
> 
> Oh, and feel free to add any of this to the operational dashboard that makes sense. I think there's a compaction section now.

Agree, added the level label and new metric, and added both new metrics to the operational dashboard.  I am not 100% satisfied with `sum(increase(tempodb_compaction_blocks_total[5m]))` but different sum intervals ($__interval, $__rate_interval, [1m]) lead to poor quality graphs in local testing.

I'm inclined to leave the duration metric for now, while we settle on the best KPIs for compaction.

2020-11-20 18:37 UTC, joe-elliott requested changes
A couple of final touches and it will be ready to merge.  Also make sure to list the removed metric in the changelog.  Thanks!

2020-11-20 18:37 UTC, joe-elliott commented on operations/tempo-mixin/tempo-operational.json
> +            "expr": "sum(rate(tempodb_compaction_objects_processed_total[$__rate_interval])) by (level)",
this needs to  respect the namespace and cluster variables.

2020-11-20 18:37 UTC, joe-elliott commented on operations/tempo-mixin/tempo-operational.json
> +            "expr": "sum(increase(tempodb_compaction_blocks_total[5m])) by (level)",
samesies

2020-11-20 18:37 UTC, joe-elliott commented on tempodb/compactor.go
>  	metricCompactionDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
remove this metric

2020-11-23 15:28 UTC, mdisibio commented on tempodb/compactor.go
>  	metricCompactionDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
Removed

2020-11-23 16:03 UTC, joe-elliott approved these changes

2020-11-23 16:03 UTC, merged