[DOC] Update tempo-distributed helm chart doc
grafana/tempo pull request #4370
Opened 2024-11-23 03:14 UTC by knylander-grafana

**What this PR does**:

Update Helm chart procedures for accuracy.

**Which issue(s) this PR fixes**:
Related: 

**Checklist**
- [ ] Tests updated
- [X] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2024-11-23 03:21 UTC, knylander-grafana commented on docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
> +Refer to the [`storage` configuration block](httpe://docs/tempo/<TEMPO_VERSION>/configuration#storage) for information on storage options.
```suggestion
Refer to the [`storage` configuration block](https://grafana.com/docs/tempo/<TEMPO_VERSION>/configuration#storage) for information on storage options.
```

2024-11-25 16:59 UTC, ie-pham approved these changes

2024-11-25 19:08 UTC, ayah-el requested changes
A few suggested fixes

2024-11-25 19:08 UTC, ayah-el commented on docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
> +However, you can use a other storage provides.
```suggestion
However, you can use another storage provider.
```

2024-11-25 19:08 UTC, ayah-el commented on docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
> +This procedure only covers the minimum required to launch GET or Tempo in a basic deployment.
```suggestion
This procedure only covers the minimum configuration required to launch GET or Tempo in a basic deployment.
```

2024-11-25 19:08 UTC, ayah-el commented on docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
> +If you are a Linux systems and it's not possible for you set up local DNS resolution, use the `--add-host=<ingress-host>:<kubernetes-cluster-external-address>` command-line flag to define the `<ingre
```suggestion
If you are using a Linux system and it's not possible for you set up local DNS resolution, use the `--add-host=<ingress-host>:<kubernetes-cluster-external-address>` command-line flag to define the `<ingress-host>` local address for the Docker commands in the examples that follow.
```

2024-11-25 19:17 UTC, knylander-grafana commented on docs/sources/helm-charts/tempo-distributed/get-started-helm-charts/_index.md
> +If you are a Linux systems and it's not possible for you set up local DNS resolution, use the `--add-host=<ingress-host>:<kubernetes-cluster-external-address>` command-line flag to define the `<ingre
Very good catch on this.

2024-11-25 20:01 UTC, knylander-grafana commented
> A few suggested fixes

Done. would you review again?

2024-11-25 20:07 UTC, ayah-el approved these changes
lgtm ✅

2024-11-26 02:07 UTC, merged