Improved query docs
grafana/tempo pull request #794
Opened 2021-06-24 14:34 UTC by joe-elliott

**What this PR does**:
- Adds details about return value of the querier endpoint
- Changed heading for `/api/echo` to better reflect what it does. (don't want to get mixed up with k8s /readiness handlers)

2021-06-24 18:21 UTC, joe-elliott commented on docs/tempo/website/api_docs/_index.md
> +but if it can also send OpenTelemetry proto if `Accept: application/protobuf` is passed.
https://developers.google.com/protocol-buffers

2021-06-24 19:06 UTC, kvrhdn requested changes
Good call to rename the echo endpoint, readiness is confusing :+1:

You'll also have to update the table at the top of this page.

2021-06-24 19:34 UTC, kvrhdn approved these changes
Besides the section link, LGTM 🙂

2021-06-24 19:34 UTC, kvrhdn commented on docs/tempo/website/api_docs/_index.md
> +| [Query Echo Endpoint](#query-path-readiness-check) | Query-frontend |  HTTP | `GET /api/echo` |
```suggestion
| [Query Echo Endpoint](#query-echo-endpoint) | Query-frontend |  HTTP | `GET /api/echo` |
```

2021-06-25 05:29 UTC, annanay25 approved these changes

2021-06-25 05:29 UTC, merged